version: '3.5'

services:
  db:
    container_name: mimimi-db
    ports:
      - "5666:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=mimimi
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - ./postgres/data.sql:/docker-entrypoint-initdb.d/data.sql

  api:
    container_name: mimimi-api
    image: sansensekai/mimimi-api
    ports:
      - "8081:9900"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mimimi
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect

  web:
    container_name: mimimi-web
    image: sansensekai/mimimi-web
    ports:
      - "3000:3000"
    depends_on:
      - api